services:
  web1:
    image: "nuxt-with-docker"
    restart: "always"
    ports:
      - "8080:8080"
  web2:
    image: "nuxt-with-docker"
    restart: "always"
    ports:
      - "8081:8080"
  web3:
    image: "nuxt-with-docker"
    restart: "always"
    ports:
      - "8082:8080"
  web4:
    image: "nuxt-with-docker"
    restart: "always"
    ports:
      - "8083:8080"
